### ISSUE TITLE
Proper Styling Of Book Section

### ISSUE THREAD

**Issue by AmanSingh6574** [jayk-gupta/web-resources-project#26] opened 2023-05-20 14:05 UTC
Issue - 
1. The Content is not aligned properly.
2. Font Family is not proper.

![image](https://github.com/jayk-gupta/web-resources-project/assets/113782984/4c091589-8599-404f-95bb-0ea7ffe79c69)

I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23. @jayk-gupta 
@mhdamaan79

**Comment by ARGHYADIPROY** [comment] 2023-05-20 14:29
I am a GSSoC'23 contributor. I will change the styling of the Book section. 
Please assign me this issue , I want to work on this issue under the GSSoC'23.

**Comment by AmanSingh6574** [comment] 2023-05-20 14:35
I have already raised this issue.

**Comment by ayesha-firdaus** [comment] 2023-05-20 15:58
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by ARGHYADIPROY** [comment] 2023-05-20 17:33
Please assign me this issue , I want to work on this issue under the GSSoC'23.

**Comment by mhdamaan79** [comment] 2023-05-21 03:59
Someone has already raised the same issue.

**Closed** 2023-05-23 05:41 UTC
