### ISSUE TITLE
Center welcome text in Books section

### ISSUE THREAD

**Issue by pearlrathour** [jayk-gupta/web-resources-project#9] opened 2023-05-20 07:22 UTC
![image](https://github.com/jayk-gupta/web-resources-project/assets/99817664/f2d2c30f-16b5-4c1a-b66b-60ae835d0575)

This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.

**Comment by Avinash905** [comment] 2023-05-20 07:37
I would like to work on this issue under GSSOC-23

**Comment by bkrayaguru931** [comment] 2023-05-20 07:42
I am working on it under GSSoC'23

**Comment by bkrayaguru931** [comment] 2023-05-20 07:44
> I would like to work on this issue under GSSOC-23

Are you working?

**Comment by Avinash905** [comment] 2023-05-20 08:21
> > I would like to work on this issue under GSSOC-23
> 
> Are you working?

The issue has not been assigned to me yet

**Comment by bkrayaguru931** [comment] 2023-05-20 08:53
@jayk-gupta I found a solution to this issue. Could you please assign me this task to make a pull request under gssoc'23.

**Comment by lalitkumawat1m** [comment] 2023-05-20 13:07
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by ayesha-firdaus** [comment] 2023-05-20 15:59
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by jayk-gupta** [comment] 2023-05-20 16:32
> ![image](https://user-images.githubusercontent.com/99817664/239673723-f2d2c30f-16b5-4c1a-b66b-60ae835d0575.png)
> 
> This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.

Do you like to work on it?

**Comment by ayesha-firdaus** [comment] 2023-05-20 16:33
yes

**Comment by Avinash905** [comment] 2023-05-20 16:56
> > ![image](https://user-images.githubusercontent.com/99817664/239673723-f2d2c30f-16b5-4c1a-b66b-60ae835d0575.png)
> > This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.
> 
> Do you like to work on it?

Yes, I would like to work on this issue

**Comment by pearlrathour** [comment] 2023-05-21 05:11
> > ![image](https://user-images.githubusercontent.com/99817664/239673723-f2d2c30f-16b5-4c1a-b66b-60ae835d0575.png)
> > This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.
> 
> Do you like to work on it?

Yes I would like to work on this issue.

**Comment by jayk-gupta** [comment] 2023-05-21 05:59
> > > ![image](https://user-images.githubusercontent.com/99817664/239673723-f2d2c30f-16b5-4c1a-b66b-60ae835d0575.png)
> > > This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.
> > 
> > 
> > Do you like to work on it?
> 
> Yes I would like to work on this issue.

Are you in GSSoc'23?

**Comment by pearlrathour** [comment] 2023-05-21 07:46
> > > > ![image](https://user-images.githubusercontent.com/99817664/239673723-f2d2c30f-16b5-4c1a-b66b-60ae835d0575.png)
> > > > This issue affects the overall aesthetics and user experience of the website. It would be great to have the welcome line properly centered in the Book section.
> > > 
> > > 
> > > Do you like to work on it?
> > 
> > 
> > Yes I would like to work on this issue.
> 
> Are you in GSSoc'23?

Yes

**Closed** 2023-05-23 05:37 UTC
Labels: GSSoC'23, level-1
