### ISSUE TITLE
Improving the nav file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [jayk-gupta/web-resources-project#14] opened 2023-05-20 08:04 UTC
I would like to improve the nav file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment] 2023-05-20 08:05
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by pjoshi999** [comment] 2023-05-20 08:48
Hi @jayk-gupta, hope you are doing good, I have been practicing react for long time and if you assign this task to me, I'd be grateful.
Thank You

**Comment by tanya2203** [comment] 2023-05-20 12:17
I will design an attractive and visually appealing nav file that complements the overall theme and aesthetics of your web app. By using colour schemes, typography, and icons that align with your branding and create an appealing visual experience.
Please assign this issue to me.

**Comment by harshsingh32** [comment] 2023-05-20 12:19
I have relevant experience and skill set to improve the UI of the page using the attractive colour scheme and engaging fonts, that engage the users to contribute to the repo and increase the engagement of this project.

**Comment by ayesha-firdaus** [comment] 2023-05-20 15:58
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by jayk-gupta** [comment] 2023-05-26 07:00
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin

**Closed by jayk-gupta** 2023-05-26 07:00 UTC
Labels: GSSoC'23, UI
